// <auto-generated />
using Labb4.API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Labb4.API.Migrations
{
    [DbContext(typeof(Labb4DbContext))]
    [Migration("20220330100409_initialCreate")]
    partial class initialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Labb4.Models.Interest", b =>
                {
                    b.Property<int>("InterestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InterestId");

                    b.HasIndex("PersonId");

                    b.ToTable("Interests");

                    b.HasData(
                        new
                        {
                            InterestId = 1,
                            Description = "Spela Golf",
                            PersonId = 1,
                            Title = "Golf"
                        },
                        new
                        {
                            InterestId = 2,
                            Description = "Köra Fort",
                            PersonId = 2,
                            Title = "Racing"
                        },
                        new
                        {
                            InterestId = 3,
                            Description = "Skjuta vilt",
                            PersonId = 3,
                            Title = "Skytte"
                        });
                });

            modelBuilder.Entity("Labb4.Models.Link", b =>
                {
                    b.Property<int>("LinkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("InterestId")
                        .HasColumnType("int");

                    b.Property<string>("URL")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LinkId");

                    b.HasIndex("InterestId");

                    b.ToTable("Links");

                    b.HasData(
                        new
                        {
                            LinkId = 1,
                            InterestId = 1,
                            URL = "https://www.vinbergsgolfklubb.se/"
                        },
                        new
                        {
                            LinkId = 2,
                            InterestId = 2,
                            URL = "https://www.falkenbergsmk.se/"
                        },
                        new
                        {
                            LinkId = 3,
                            InterestId = 3,
                            URL = "https://www.pistolskytteforbundet.se/"
                        });
                });

            modelBuilder.Entity("Labb4.Models.Person", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PersonId");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            PersonId = 1,
                            Adress = "Hertings Allé 5A",
                            FirstName = "Lucas",
                            LastName = "Narfgren",
                            Phone = "0707409223"
                        },
                        new
                        {
                            PersonId = 2,
                            Adress = "Kalles Allé 5A",
                            FirstName = "Johnny",
                            LastName = "karlsson",
                            Phone = "034534423"
                        },
                        new
                        {
                            PersonId = 3,
                            Adress = "Svens Allé 5A",
                            FirstName = "Conny",
                            LastName = "Svensson",
                            Phone = "098098764"
                        });
                });

            modelBuilder.Entity("Labb4.Models.Interest", b =>
                {
                    b.HasOne("Labb4.Models.Person", "Person")
                        .WithMany("Interests")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Labb4.Models.Link", b =>
                {
                    b.HasOne("Labb4.Models.Interest", "Interest")
                        .WithMany()
                        .HasForeignKey("InterestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
